sudo: required
dist: focal
services:
  - docker

env:
  global:
    - SHA=$(git rev-parse HEAD) 
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1 # config google cloud cli to not ask for user input promotes

before_install:
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d

  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  
  - gcloud config set project mimetic-heaven-418713
  - gcloud config set compute/zone us-central1-c
  - gcloud container clusters get-credentials task-manager-cluster

  - echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_ID --password-stdin
  - docker build -f ./client/Dockerfile.dev -t 315426346/task-manager-client-dev:latest ./client


script:
  - docker run -e CI=true 315426346/task-manager-client-dev npm run test


deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: main