apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: api
  template:
    metadata:
      labels: 
        component: api
    spec:
      containers:
        - name: api-container
          ports:
            - containerPort: 4002
          image: 315426346/task-manager-api
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_SECRET
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  key: PGPASSWORD
                  name: pgpassword
            - name: PGUSER
              value: postgres
            - name: PGDATABASE
              value: postgres
            - name: PG_PORT
              value: "5432"
            - name: PGHOST
              value: postgres-service

--- 

apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    component: api
  type: ClusterIP
  ports:
    - port: 4002
      targetPort: 4002


